language: python
python:
  - "3.6"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
  - "pip install -e ."
script:
  - ansunit asp/tests.yaml
  - pytest --cov=draco
addons:
  apt:
    packages:
    - gringo
after_success:
    - coveralls
